name: Docker Image for Laravel

on:
  push:

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: |
          docker login -u kizoukun -p ${{ secrets.GH_TOKEN }} ghcr.io
          docker build . --tag ghcr.io/kizoukun/db-trading:latest
          docker push ghcr.io/kizoukun/db-trading:latest
